
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php81-fpm
    volumes:
      - ./:/var/www/html:cached
      - ./php/conf.d:/usr/local/etc/php/conf.d
    environment:
      # Xdebug dynamisch einschalten/konfigurieren:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: "9003"
      XDEBUG_IDEKEY: "PHPSTORM"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - web

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - web

networks:
  web:
    driver: bridge
